### ISSUE TITLE
Angular 18 compatibility

### ISSUE THREAD

**Issue by AntonioCPJunior** [ChellappanRajan/ngx-confetti-explosion#15]
It's not building to Angular v18 . Could you release a updated version to support Angular v18?

Run npm ci
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: ngx-confetti-explosion@3.0.1
npm error Found: @angular/common@18.2.10
npm error node_modules/@angular/common
npm error   @angular/common@"^18.2.10" from the root project
npm error   peer @angular/common@"^18.0.0 || ^19.0.0" from @angular/cdk@18.2.11
npm error   node_modules/@angular/cdk
npm error     @angular/cdk@"^18.2.11" from the root project
npm error   16 more (@angular/forms, @angular/platform-browser, ...)
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"^17" from ngx-confetti-explosion@3.0.1
npm error node_modules/ngx-confetti-explosion
npm error   ngx-confetti-explosion@"^3.0.1" from the root project
npm error
npm error Conflicting peer dependency: @angular/common@17.3.12
npm error node_modules/@angular/common
npm error   peer @angular/common@"^17" from ngx-confetti-explosion@3.0.1
npm error   node_modules/ngx-confetti-explosion
npm error     ngx-confetti-explosion@"^3.0.1" from the root project

**Comment by ChellappanRajan** [comment]
Thanks for reporting, I have updated please try latest version and let me know if you facing any issues.
